class CreateSkillsheets < ActiveRecord::Migration
  def change
    create_table :skillsheets do |t|
      t.references :character, index: true

      t.timestamps
    end
    add_column :skillsheets, :acrobTot, :integer
    add_column :skillsheets, :appraTot, :integer
    add_column :skillsheets, :bluffTot, :integer
    add_column :skillsheets, :climbTot, :integer
    add_column :skillsheets, :craf1Tot, :integer
    add_column :skillsheets, :craf2Tot, :integer
    add_column :skillsheets, :craf3Tot, :integer
    add_column :skillsheets, :diploTot, :integer
    add_column :skillsheets, :disabTot, :integer
    add_column :skillsheets, :disguTot, :integer
    add_column :skillsheets, :escapTot, :integer
    add_column :skillsheets, :flyTot, :integer
    add_column :skillsheets, :handlTot, :integer
    add_column :skillsheets, :healTot, :integer
    add_column :skillsheets, :intimTot, :integer
    add_column :skillsheets, :kArcaTot, :integer
    add_column :skillsheets, :kDungTot, :integer
    add_column :skillsheets, :kEngiTot, :integer
    add_column :skillsheets, :kGeogTot, :integer
    add_column :skillsheets, :kHistTot, :integer
    add_column :skillsheets, :kLocaTot, :integer
    add_column :skillsheets, :kNatuTot, :integer
    add_column :skillsheets, :kNobiTot, :integer
    add_column :skillsheets, :kPlanTot, :integer
    add_column :skillsheets, :kReliTot, :integer
    add_column :skillsheets, :linguTot, :integer
    add_column :skillsheets, :perceTot, :integer
    add_column :skillsheets, :perf1Tot, :integer
    add_column :skillsheets, :perf2Tot, :integer
    add_column :skillsheets, :prof1Tot, :integer
    add_column :skillsheets, :prof2Tot, :integer
    add_column :skillsheets, :rideTot, :integer
    add_column :skillsheets, :senseTot, :integer
    add_column :skillsheets, :sleigTot, :integer
    add_column :skillsheets, :spellTot, :integer
    add_column :skillsheets, :stealTot, :integer
    add_column :skillsheets, :surviTot, :integer
    add_column :skillsheets, :swimTot, :integer
    add_column :skillsheets, :useMaTot, :integer


    add_column :skillsheets, :acrobAbl, :integer
    add_column :skillsheets, :appraAbl, :integer
    add_column :skillsheets, :bluffAbl, :integer
    add_column :skillsheets, :climbAbl, :integer
    add_column :skillsheets, :craf1Abl, :integer
    add_column :skillsheets, :craf2Abl, :integer
    add_column :skillsheets, :craf3Abl, :integer
    add_column :skillsheets, :diploAbl, :integer
    add_column :skillsheets, :disabAbl, :integer
    add_column :skillsheets, :disguAbl, :integer
    add_column :skillsheets, :escapAbl, :integer
    add_column :skillsheets, :flyAbl, :integer
    add_column :skillsheets, :handlAbl, :integer
    add_column :skillsheets, :healAbl, :integer
    add_column :skillsheets, :intimAbl, :integer
    add_column :skillsheets, :kArcaAbl, :integer
    add_column :skillsheets, :kDungAbl, :integer
    add_column :skillsheets, :kEngiAbl, :integer
    add_column :skillsheets, :kGeogAbl, :integer
    add_column :skillsheets, :kHistAbl, :integer
    add_column :skillsheets, :kLocaAbl, :integer
    add_column :skillsheets, :kNatuAbl, :integer
    add_column :skillsheets, :kNobiAbl, :integer
    add_column :skillsheets, :kPlanAbl, :integer
    add_column :skillsheets, :kReliAbl, :integer
    add_column :skillsheets, :linguAbl, :integer
    add_column :skillsheets, :perceAbl, :integer
    add_column :skillsheets, :perf1Abl, :integer
    add_column :skillsheets, :perf2Abl, :integer
    add_column :skillsheets, :prof1Abl, :integer
    add_column :skillsheets, :prof2Abl, :integer
    add_column :skillsheets, :rideAbl, :integer
    add_column :skillsheets, :senseAbl, :integer
    add_column :skillsheets, :sleigAbl, :integer
    add_column :skillsheets, :spellAbl, :integer
    add_column :skillsheets, :stealAbl, :integer
    add_column :skillsheets, :surviAbl, :integer
    add_column :skillsheets, :swimAbl, :integer
    add_column :skillsheets, :useMaAbl, :integer

    add_column :skillsheets, :acrobRan, :integer
    add_column :skillsheets, :appraRan, :integer
    add_column :skillsheets, :bluffRan, :integer
    add_column :skillsheets, :climbRan, :integer
    add_column :skillsheets, :craf1Ran, :integer
    add_column :skillsheets, :craf2Ran, :integer
    add_column :skillsheets, :craf3Ran, :integer
    add_column :skillsheets, :diploRan, :integer
    add_column :skillsheets, :disabRan, :integer
    add_column :skillsheets, :disguRan, :integer
    add_column :skillsheets, :escapRan, :integer
    add_column :skillsheets, :flyRan, :integer
    add_column :skillsheets, :handlRan, :integer
    add_column :skillsheets, :healRan, :integer
    add_column :skillsheets, :intimRan, :integer
    add_column :skillsheets, :kArcaRan, :integer
    add_column :skillsheets, :kDungRan, :integer
    add_column :skillsheets, :kEngiRan, :integer
    add_column :skillsheets, :kGeogRan, :integer
    add_column :skillsheets, :kHistRan, :integer
    add_column :skillsheets, :kLocaRan, :integer
    add_column :skillsheets, :kNatuRan, :integer
    add_column :skillsheets, :kNobiRan, :integer
    add_column :skillsheets, :kPlanRan, :integer
    add_column :skillsheets, :kReliRan, :integer
    add_column :skillsheets, :linguRan, :integer
    add_column :skillsheets, :perceRan, :integer
    add_column :skillsheets, :perf1Ran, :integer
    add_column :skillsheets, :perf2Ran, :integer
    add_column :skillsheets, :prof1Ran, :integer
    add_column :skillsheets, :prof2Ran, :integer
    add_column :skillsheets, :rideRan, :integer
    add_column :skillsheets, :senseRan, :integer
    add_column :skillsheets, :sleigRan, :integer
    add_column :skillsheets, :spellRan, :integer
    add_column :skillsheets, :stealRan, :integer
    add_column :skillsheets, :surviRan, :integer
    add_column :skillsheets, :swimRan, :integer
    add_column :skillsheets, :useMaRan, :integer

    add_column :skillsheets, :acrobMod, :integer
    add_column :skillsheets, :appraMod, :integer
    add_column :skillsheets, :bluffMod, :integer
    add_column :skillsheets, :climbMod, :integer
    add_column :skillsheets, :craf1Mod, :integer
    add_column :skillsheets, :craf2Mod, :integer
    add_column :skillsheets, :craf3Mod, :integer
    add_column :skillsheets, :diploMod, :integer
    add_column :skillsheets, :disabMod, :integer
    add_column :skillsheets, :disguMod, :integer
    add_column :skillsheets, :escapMod, :integer
    add_column :skillsheets, :flyMod, :integer
    add_column :skillsheets, :handlMod, :integer
    add_column :skillsheets, :healMod, :integer
    add_column :skillsheets, :intimMod, :integer
    add_column :skillsheets, :kArcaMod, :integer
    add_column :skillsheets, :kDungMod, :integer
    add_column :skillsheets, :kEngiMod, :integer
    add_column :skillsheets, :kGeogMod, :integer
    add_column :skillsheets, :kHistMod, :integer
    add_column :skillsheets, :kLocaMod, :integer
    add_column :skillsheets, :kNatuMod, :integer
    add_column :skillsheets, :kNobiMod, :integer
    add_column :skillsheets, :kPlanMod, :integer
    add_column :skillsheets, :kReliMod, :integer
    add_column :skillsheets, :linguMod, :integer
    add_column :skillsheets, :perceMod, :integer
    add_column :skillsheets, :perf1Mod, :integer
    add_column :skillsheets, :perf2Mod, :integer
    add_column :skillsheets, :prof1Mod, :integer
    add_column :skillsheets, :prof2Mod, :integer
    add_column :skillsheets, :rideMod, :integer
    add_column :skillsheets, :senseMod, :integer
    add_column :skillsheets, :sleigMod, :integer
    add_column :skillsheets, :spellMod, :integer
    add_column :skillsheets, :stealMod, :integer
    add_column :skillsheets, :surviMod, :integer
    add_column :skillsheets, :swimMod, :integer
    add_column :skillsheets, :useMaMod, :integer

  end
end
